### PR TITLE
qemu: Fix aarch64-linux again

### PR DESCRIPTION
**Pull request by mikatammi**

### CODE REVIEW

**Comment by mikatammi** [comment]
@astro I have few questions before you shovel this in

I removed the extraneous kernel and initrd arguments, and conditionalized the serial devices based on whether it is x86_64-linux and aarch64-linux, this seemed to be a crucial bit or otherwise the VM wouldn't start at all on arm64. Now the QEMU microvm works on both x86_64 and aarch64 again, however I don't get any log to system journal on aarch64, only on x86_64, but it still works.

**Comment by astro** [comment]
Can you please rebase again? I already spotted and removed the duplicate qemu args last night before I read this PR. Sorry.

The `console=hvc0` param is no longer valid because I dropped the `result/bin/microvm-console` feature. For debugging the output, I'd start by comparing `dmesg | grep tty` on x86_64 and aarch64. I'm happy to receive this in another PR.

**Comment by mikatammi** [comment]
I fixed the PR, on aarch64-linux the guest kernel simply does not want earlyprintk=ttyS0 and console=ttyS0 parameters. Removing them makes VM to boot and even the log is visible in the terminal now, even though it does not have any console parameters.

**Comment by mikatammi** [comment]
On x86_64-linux I get:
```
$ dmesg | grep tty
[    0.000000] Command line: earlyprintk=ttyS0 console=ttyS0 reboot=t panic=-1 init=/nix/store/rifc6y3hvy085vyzs1zjb6244vadr6kq-nixos-system-netvm-23.05.20230528.a7adead/init regInfo=/nix/store/xbhgnkh9jmj1s8s71f7nsa1bvvmgv73g-closure-info/registration
[    0.042069] Kernel command line: earlyprintk=ttyS0 console=ttyS0 reboot=t panic=-1 init=/nix/store/rifc6y3hvy085vyzs1zjb6244vadr6kq-nixos-system-netvm-23.05.20230528.a7adead/init regInfo=/nix/store/xbhgnkh9jmj1s8s71f7nsa1bvvmgv73g-closure-info/registration
[    0.063468] printk: console [ttyS0] enabled
[    0.279006] 00:02: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a 16550A
[    1.342047] systemd[1]: Created slice Slice /system/getty.
[    1.343921] systemd[1]: Created slice Slice /system/serial-getty.
```

On aarch64-linux I get:
```
$ dmesg | grep tty
[    0.000208] printk: console [tty0] enabled
[    0.012785] 9000000.pl011: ttyAMA0 at MMIO 0x9000000 (irq = 13, base_baud = 0) is a PL011 rev1
[    0.115946] printk: console [ttyAMA0] enabled
[    2.738893] systemd[1]: Created slice Slice /system/getty.
[    2.744176] systemd[1]: Created slice Slice /system/serial-getty.
```

**Comment by astro** [comment]
Did you check if you see more of the boot process on aarch64 if you launch with `earlyprintk=ttyAMA0 console=ttyAMA0`?

**Comment by mikatammi** [comment]
I can check

**Comment by mikatammi** [comment]
Without those `earlyprintk=ttyAMA0 console=ttyAMA0` added I get:
```
-- Boot 664e0aca4863416e993746a8d676a2a0 --
-- Boot 664e0aca4863416e993746a8d676a2a0 --
Jun 21 17:19:11 ghaf-host systemd[1]: Starting MicroVM 'netvm-nvidia-jetson-orin-debug'...
Jun 21 17:19:11 ghaf-host systemd[1]: Started MicroVM 'netvm-nvidia-jetson-orin-debug'.
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd421]
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] Linux version 6.1.30 (nixbld@localhost) (gcc (GCC) 12.2.0, GNU ld (GNU Binutils) 2.40) #1-NixOS SMP Wed May 24 16:32:53 UTC 2023
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] random: crng init done
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] Machine model: linux,dummy-virt
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] efi: UEFI not found.
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] NUMA: No NUMA configuration found
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] NUMA: Faking a node at [mem 0x0000000040000000-0x000000005fffffff]
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] NUMA: NODE_DATA [mem 0x5fef59c0-0x5fef8fff]
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] Zone ranges:
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000]   DMA      [mem 0x0000000040000000-0x000000005fffffff]
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000]   DMA32    empty
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000]   Normal   empty
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000]   Device   empty
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] Movable zone start for each node
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] Early memory node ranges
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000]   node   0: [mem 0x0000000040000000-0x000000005fffffff]
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] Initmem setup node 0 [mem 0x0000000040000000-0x000000005fffffff]
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] cma: Reserved 32 MiB at 0x000000005d600000
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] psci: probing for conduit method from DT.
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] psci: PSCIv1.0 detected in firmware.
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] psci: Using standard PSCI v0.2 function IDs
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] psci: Trusted OS migration not required
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] psci: SMC Calling Convention v1.1
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] percpu: Embedded 30 pages/cpu s84008 r8192 d30680 u122880
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] Detected PIPT I-cache on CPU0
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] CPU features: detected: GIC system register CPU interface
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] CPU features: detected: Hardware dirty bit management
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] CPU features: detected: Spectre-v4
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] CPU features: detected: Spectre-BHB
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] CPU features: kernel page table isolation forced ON by KASLR
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] CPU features: detected: Kernel page table isolation (KPTI)
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] alternatives: applying boot alternatives
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] Fallback order for Node 0: 0
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 129024
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] Policy zone: DMA
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] Kernel command line: edd=off reboot=t panic=-1 init=/nix/store/0w2qv4334bdwvm0m1g9b84i905ql6h1d-nixos-system-netvm-23.05.20230528.a7adead>
Jun 21 17:19:16 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1158]: [    0.000000] Unknown kernel command line parameters "edd=off regInfo=/nix/store/alccf7jqz7xlfbvj5h10wmrracy4vzvm-closure-info/registration", will be p>
```


If I add those, I get:
```
-- Boot 004a7dd158de4788a86067c516ed32a3 --
Jun 21 17:23:19 ghaf-host systemd[1]: Starting MicroVM 'netvm-nvidia-jetson-orin-debug'...
Jun 21 17:23:19 ghaf-host systemd[1]: Started MicroVM 'netvm-nvidia-jetson-orin-debug'.
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd421]
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] Linux version 6.1.30 (nixbld@localhost) (gcc (GCC) 12.2.0, GNU ld (GNU Binutils) 2.40) #1-NixOS SMP Wed May 24 16:32:53 UTC 2023
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] random: crng init done
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] Machine model: linux,dummy-virt
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] efi: UEFI not found.
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] NUMA: No NUMA configuration found
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] NUMA: Faking a node at [mem 0x0000000040000000-0x000000005fffffff]
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] NUMA: NODE_DATA [mem 0x5fef59c0-0x5fef8fff]
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] Zone ranges:
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000]   DMA      [mem 0x0000000040000000-0x000000005fffffff]
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000]   DMA32    empty
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000]   Normal   empty
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000]   Device   empty
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] Movable zone start for each node
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] Early memory node ranges
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000]   node   0: [mem 0x0000000040000000-0x000000005fffffff]
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] Initmem setup node 0 [mem 0x0000000040000000-0x000000005fffffff]
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] cma: Reserved 32 MiB at 0x000000005d600000
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] psci: probing for conduit method from DT.
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] psci: PSCIv1.0 detected in firmware.
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] psci: Using standard PSCI v0.2 function IDs
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] psci: Trusted OS migration not required
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] psci: SMC Calling Convention v1.1
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] percpu: Embedded 30 pages/cpu s84008 r8192 d30680 u122880
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] Detected PIPT I-cache on CPU0
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] CPU features: detected: GIC system register CPU interface
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] CPU features: detected: Hardware dirty bit management
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] CPU features: detected: Spectre-v4
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] CPU features: detected: Spectre-BHB
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] CPU features: kernel page table isolation forced ON by KASLR
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] CPU features: detected: Kernel page table isolation (KPTI)
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] alternatives: applying boot alternatives
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] Fallback order for Node 0: 0
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 129024
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] Policy zone: DMA
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] Kernel command line: earlyprintk=ttyAMA0 console=ttyAMA0 edd=off reboot=t panic=-1 init=/nix/store/0w2qv4334bdwvm0m1g9b84i905ql6h1d-nixos>
Jun 21 17:23:24 ghaf-host microvm@netvm-nvidia-jetson-orin-debug[1162]: [    0.000000] Unknown kernel command line parameters "earlyprintk=ttyAMA0 edd=off regInfo=/nix/store/alccf7jqz7xlfbvj5h10wmrracy4vzvm-closure-info/regi>
```


Noting the message about unknown kernel command line parameters I guess also edd=off could be removed and earlyprintk=ttyAMA0 is not needed for aarch64-linux

**Comment by mikatammi** [comment]
I added `console=ttyAMA0` for aarch64-linux even though it doesn't seem to change anything

**Comment by astro** [comment]
Well, thanks anyway :)

**Pull request merged**
