### PR TITLE
nixos-modules/microvm/options: add bridge to interface type

### PR DESCRIPTION
**Pull request by GTrunSec**
responses to #16

### CODE REVIEW

**Comment by astro** [comment]
Could you please write bridge support or nicely readable exceptions for the other four hypervisors? Being able to switch between them is a big feature of this project.

**Comment by GTrunSec** [comment]
No problem, I will add it by tomorrow.

**Comment by GTrunSec** [comment]
How to run the nested bridge in microvm

```
# /var/lib/microvms/bridge_qemu_2/current/bin/microvm-run       
failed to add interface `tap0' to bridge `enp0s6': Operation not supported
qemu-system-x86_64: -netdev bridge,br=enp0s6,id=vm-qemu2: bridge helper failed
``

**Comment by astro** [comment]
Add the interface with `tunctl`

Does this functionality require running the hypervisor+microvm as root? I dislike putting in such a requirement that will encourage people to run more stuff as root.

The `microvm-tap-interfaces@` systemd unit in the **host** module takes care of creating tap interfaces. I use *systemd-networkd* to attach them to a bridge. I guess there are more solutions to this but attaching interfaces to a bridge can**not** be done by non-root users, right? If so, I think it should not be done by the hypervisor.

**Comment by GTrunSec** [comment]
>  I guess there are more solutions to this, but attaching interfaces to a bridge cannot be done by non-root users, right? If so, I think it should not be done by the hypervisor.

Yes, it requires the root user for a bridge mode. But, I think I can be solved by security.wrapper to `qemu-bridge-helper`(ref to services.libvirtd.qemu.runAsRoot = false;)

the flags will be:
```
-netdev bridge,br=virbr0,helper=/run/wrappers/bin/qemu-bridge-helper,id=vm-qemutap:
```
I'm not sure that I did a correct flag of the helper.

furthermore, How do you use ssh to connect tap microm in different networks?
port forward to hostfwd=tcp::2222-:22 ? I'm sorry about the weak knowledge of VM I am.

```
ssh -p  2222 localhost ?
```

**Pull request merged**
